// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = SerieHomepageSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SerieDocumentDataSlicesSlice = SerieMainInfosSlice;

/**
 * Content for Serie documents
 */
interface SerieDocumentData {
  /**
   * Slice Zone field in *Serie*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: serie.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SerieDocumentDataSlicesSlice> /**
   * Meta Description field in *Serie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: serie.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Serie*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: serie.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Serie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: serie.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Serie document from Prismic
 *
 * - **API ID**: `serie`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SerieDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SerieDocumentData>, "serie", Lang>;

export type AllDocumentTypes = PageDocument | SerieDocument;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Présentation field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.presentation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  presentation: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SerieHomepage → Items*
 */
export interface SerieHomepageSliceDefaultItem {
  /**
   * Série field in *SerieHomepage → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: serie_homepage.items[].serie
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  serie: prismic.ContentRelationshipField<"serie">;
}

/**
 * Default variation for SerieHomepage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SerieHomepageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SerieHomepageSliceDefaultItem>
>;

/**
 * Slice variation for *SerieHomepage*
 */
type SerieHomepageSliceVariation = SerieHomepageSliceDefault;

/**
 * SerieHomepage Shared Slice
 *
 * - **API ID**: `serie_homepage`
 * - **Description**: SerieHomepage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SerieHomepageSlice = prismic.SharedSlice<
  "serie_homepage",
  SerieHomepageSliceVariation
>;

/**
 * Primary content in *SerieMainInfos → Primary*
 */
export interface SerieMainInfosSliceDefaultPrimary {
  /**
   * Title field in *SerieMainInfos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: serie_main_infos.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Presentation field in *SerieMainInfos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: serie_main_infos.primary.presentation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  presentation: prismic.RichTextField;
}

/**
 * Default variation for SerieMainInfos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SerieMainInfosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SerieMainInfosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SerieMainInfos*
 */
type SerieMainInfosSliceVariation = SerieMainInfosSliceDefault;

/**
 * SerieMainInfos Shared Slice
 *
 * - **API ID**: `serie_main_infos`
 * - **Description**: SerieMainInfos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SerieMainInfosSlice = prismic.SharedSlice<
  "serie_main_infos",
  SerieMainInfosSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SerieDocument,
      SerieDocumentData,
      SerieDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SerieHomepageSlice,
      SerieHomepageSliceDefaultItem,
      SerieHomepageSliceVariation,
      SerieHomepageSliceDefault,
      SerieMainInfosSlice,
      SerieMainInfosSliceDefaultPrimary,
      SerieMainInfosSliceVariation,
      SerieMainInfosSliceDefault,
    };
  }
}
